Repository SpiNNakerManchester/SpiNNUtils, pull requests merged in 2018-02, with the labels that each got.

#44 Little util to act as a lazy list
  spinn_utilities/index_is_value.py
Labels: enhancement

#47 fixed depricated logger.warn as it does not work with FormatAdapter
  spinn_utilities/logger_utils.py
Labels: bug

#45 More Lint
  spinn_utilities/abstract_base.py
  spinn_utilities/conf_loader.py
  spinn_utilities/configs/__init__.py
  spinn_utilities/configs/camel_case_config_parser.py
  spinn_utilities/executable_finder.py
  spinn_utilities/helpful_functions.py
  spinn_utilities/index_is_value.py
  spinn_utilities/log.py
  spinn_utilities/matrix/abstract_matrix.py
  spinn_utilities/matrix/demo_matrix.py
  spinn_utilities/matrix/double_dict.py
  spinn_utilities/matrix/x_view.py
  spinn_utilities/matrix/y_view.py
  spinn_utilities/ordered_set.py
  spinn_utilities/overrides.py
  spinn_utilities/package_loader.py
  spinn_utilities/progress_bar.py
  spinn_utilities/ranged/abstract_dict.py
  spinn_utilities/ranged/abstract_list.py
  spinn_utilities/ranged/abstract_sized.py
  spinn_utilities/ranged/abstract_view.py
  spinn_utilities/ranged/ids_view.py
  spinn_utilities/ranged/multiple_values_exception.py
  spinn_utilities/ranged/range_dictionary.py
  spinn_utilities/ranged/ranged_list.py
  spinn_utilities/ranged/single_view.py
  spinn_utilities/ranged/slice_view.py
  spinn_utilities/safe_eval.py
  spinn_utilities/socket_address.py
  spinn_utilities/testing/log_checker.py
  spinn_utilities/timer.py
  unittests/test_helpful_functions.py
  unittests/test_log.py
  unittests/test_ordered_set.py
  unittests/test_overrides.py
  unittests/test_socket_address.py
Labels: enhancement

#48 Allow listen port to be None
  spinn_utilities/socket_address.py
  unittests/test_helpful_functions.py
  unittests/test_socket_address.py
Labels: bug

#42 Nuke deplicate code
  spinn_utilities/helpful_functions.py
  unittests/test_helpful_functions.py
Labels: duplicate
