Repository SpiNNakerManchester/SpiNNUtils, pull requests merged in 2019-10, with the labels that each got.

#103 Add pylint checking
  .pylintrc
  .travis.yml
  spinn_utilities/citation/citation_aggregator.py
  spinn_utilities/configs/camel_case_config_parser.py
  spinn_utilities/log.py
  spinn_utilities/make_tools/converter.py
  spinn_utilities/make_tools/file_converter.py
  spinn_utilities/make_tools/replacer.py
  spinn_utilities/ordered_default_dict.py
  spinn_utilities/ordered_set.py
  spinn_utilities/package_loader.py
  spinn_utilities/ranged/abstract_sized.py
  unittests/test_ordered_default_dict.py
Labels: enhancement, minor

#104 fixed incorrect import from collections.abc
  setup.py
  spinn_utilities/ordered_default_dict.py
Labels: bug

#105 test peek
  unittests/test_ordered_set.py
Labels: enhancement
