Repository SpiNNakerManchester/SpiNNUtils, pull requests merged in 2021-02, with the labels that each got.

#135 Ranged List fix
  spinn_utilities/ranged/abstract_list.py
  spinn_utilities/ranged/range_dictionary.py
  spinn_utilities/ranged/ranged_list.py
  unittests/ranged/test_list.py
  unittests/ranged/whole_test.py
Labels: BLOCKER!

#134 Fix 965 by Adding new type Ranged List of Lists
  spinn_utilities/ranged/__init__.py
  spinn_utilities/ranged/ranged_list.py
  spinn_utilities/ranged/ranged_list_of_lists.py
  unittests/ranged/test_ranged_list_of_lists.py
Labels: enhancement

#132 Remove Python 2.7 support
  .github/workflows/python_actions.yml
  README.md
  doc/source/conf.py
  doc/source/index.rst
  requirements-test.txt
  requirements.txt
  setup.py
  spinn_utilities/abstract_base.py
  spinn_utilities/abstract_context_manager.py
  spinn_utilities/bytestring_utils.py
  spinn_utilities/citation/citation_aggregator.py
  spinn_utilities/citation/citation_updater_and_doi_generator.py
  spinn_utilities/conf_loader.py
  spinn_utilities/configs/camel_case_config_parser.py
  spinn_utilities/configs/case_sensitive_parser.py
  spinn_utilities/default_ordered_dict.py
  spinn_utilities/executable_finder.py
  spinn_utilities/helpful_functions.py
  spinn_utilities/log.py
  spinn_utilities/make_tools/replacer.py
  spinn_utilities/matrix/abstract_matrix.py
  spinn_utilities/matrix/demo_matrix.py
  spinn_utilities/matrix/double_dict.py
  spinn_utilities/ordered_set.py
  spinn_utilities/package_loader.py
  spinn_utilities/progress_bar.py
  spinn_utilities/ranged/abstract_dict.py
  spinn_utilities/ranged/abstract_list.py
  spinn_utilities/ranged/abstract_sized.py
  spinn_utilities/ranged/ids_view.py
  spinn_utilities/ranged/multiple_values_exception.py
  spinn_utilities/ranged/range_dictionary.py
  spinn_utilities/ranged/ranged_list.py
  spinn_utilities/ranged/single_view.py
  spinn_utilities/ranged/slice_view.py
  spinn_utilities/require_subclass.py
  spinn_utilities/see.py
  spinn_utilities/testing/log_checker.py
  spinn_utilities/timer.py
  unittests/abstract_base/abstract_has_constraints.py
  unittests/abstract_base/abstract_has_id.py
  unittests/abstract_base/abstract_has_label.py
  unittests/make_tools/foo/bar/.gitignore
  unittests/test_conf_loader.py
  unittests/test_overrides.py
  unittests/test_require_subclass.py
Labels: BLOCKER!, enhancement

#138 flake8
  spinn_utilities/package_loader.py
  spinn_utilities/ranged/range_dictionary.py
Labels: minor

#139 Test 3 9
  .github/workflows/python_actions.yml
  setup.py
Labels: enhancement

#142 Support for Andrew Rowley's complicated derivation case
  spinn_utilities/require_subclass.py
  unittests/test_require_subclass.py
Labels: bug

#143 Split out the list of files to put in documentation
  doc/source/conf.py
  doc/unfiltered-files.txt
Labels: enhancement, minor
